web/router.ex
defmodule Spaces.Router do
  use Spaces.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Spaces do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/loggedIn", PageController, :loggedIn


    resources "/post", PostController
    resources "/session", SessionController, only: [:index, :new]
    post "/session/slackLogin", SessionController, :slackLogin
    delete "/session/destroy", SessionController, :destroy

    get "/user", UsersController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", Spaces do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Spaces.LayoutView do
  use Spaces.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Spaces!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header text-center">
        <%# <nav role="navigation">
          <ul class="nav nav-pills"> %>
            <%= if !is_nil(Plug.Conn.get_session(@conn, :user)) do %>
              <%= button("Sign Out", method: "delete", to: session_path(@conn, :destroy), class: "btn btn-danger sign-out-btn")%>
            <% end %>
          <%# </ul>
        </nav> %>
        <a href="<%=users_path(@conn, :show)%>"><span class="logo-header">Spaces</span></a>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>