web/router.ex
defmodule Spaces.Router do
  use Spaces.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Spaces do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/loggedIn", PageController, :loggedIn


    resources "/post", PostController
    resources "/session", SessionController, only: [:index, :new]
    post "/session/slackLogin", SessionController, :slackLogin
    delete "/session/destroy", SessionController, :destroy

    get "/user", UsersController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", Spaces do
  #   pipe_through :api
  # end
end

web/models/user.ex
defmodule Spaces.User do
  use Spaces.Web, :model

  schema "users" do
    field :name, :string
    field :slack_name, :string
    field :slack_id, :string

    timestamps
  end

  @required_fields ~w(name slack_name slack_id)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/users_controller.ex
defmodule Spaces.UsersController do
  use Spaces.Web, :controller
  alias Spaces.User
  alias Spaces.Post

  require IEx

  plug Spaces.Plugs.Authentication

  def show(conn, params) do
    posts = 
      from(p in Post, where: p.user_id == ^get_user_id(conn))
      |> Repo.all
    render conn, "show.html", set_view_variables(conn, %{posts: posts})
  end

  defp set_view_variables(conn, params_map) do
    Map.put(params_map, :user_name, get_session(conn, :user) |> Map.get(:user_name))
  end

  defp get_user_id(conn) do
    get_session(conn, :user) |> Map.get(:user_id)
  end

end

web/views/users_view.ex
defmodule Spaces.UsersView do
  require IEx  
  use Spaces.Web, :view
end

web/templates/users/show.html.eex
<div class="user-header text-left clearfix">
  <span class="">Hello <span class="username"><%= @user_name%></span></span>  
  <span class="pull-right"><%= link("Create Post", to: post_path(@conn, :new))%></span>
</div>
<%= for post <- @posts do %>
  <div class="post-container text-center">
    <div class="post-title"><%= post.title%></div>
    <div class="post-body"><%= truncate(post.content, length: 500)%></div>
    <div class="post-open-link"><%=link("Continue Reading", to: post_path(@conn, :show, post.id)) %></div>
  </div>
<% end %>
  
  